networks:
  jupyterhub-network:
    name: jupyterhub-network

services:
  jupyter:
    container_name: jupyter-paypal
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/home/jupyter_user/jupyterhub_config.py
    networks:
      - jupyterhub-network
    restart: unless-stopped

  auth-service:
    container_name: auth-paypal
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - jupyterhub-network
    restart: unless-stopped
