services:
  jupyter:
    container_name: jupyter-paypal
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./notebooks:/home/jupyter_user/notebooks
      - ./data:/home/jupyter_user/data
      - ./src:/home/jupyter_user/src
    restart: unless-stopped
